module.exports = {
  // General
  REQUIRED_FIELDS_NOT_FOUND: 'REQUIRED_FIELDS_NOT_FOUND',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  // Token Responses
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',

  // Auth Responses
  NOT_AUTHORIZED: 'NOT_AUTHORIZED',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  NO_AUTHORIZATION_PROVIDED: 'NO_AUTHORIZATION_PROVIDED',

  // User Responses
  CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
  CREATE_USER_FAILURE: 'CREATE_USER_FAILURE',

  UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
  UPDATE_USER_FAILURE: 'UPDATE_USER_FAILURE',

  UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',
  UPDATE_PROFILE_FAILURE: 'UPDATE_PROFILE_FAILURE',

  UPDATE_PASSWORD_SUCCESS: 'UPDATE_PASSWORD_SUCCESS',
  UPDATE_PASSWORD_FAILURE: 'UPDATE_PASSWORD_FAILURE',

  SHOW_USER_SUCCESS: 'SHOW_USER_SUCCESS',
  SHOW_USER_FAILURE: 'SHOW_USER_FAILURE',

  SHOW_USER_POSTS_SUCCESS: 'SHOW_USER_POSTS_SUCCESS',
  SHOW_USER_POSTS_FAILURE: 'SHOW_USER_POSTS_FAILURE',

  DELETE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
  DELETE_USER_FAILURE: 'UPDATE_USER_FAILURE',

  USER_NOT_FOUND: 'USER_NOT_FOUND',
  INCORRECT_PASSWORD: 'INCORRECT_PASSWORD',

  USER_EXISTS: 'USER_EXISTS',

  // Comment Responses
  CREATE_COMMENT_SUCCESS: 'CREATE_COMMENT_SUCCESS',
  CREATE_COMMENT_FAILURE: 'CREATE_COMMENT_FAILURE',

  UPDATE_COMMENT_SUCCESS: 'UPDATE_COMMENT_SUCCESS',
  UPDATE_COMMENT_FAILURE: 'UPDATE_COMMENT_FAILURE',

  SHOW_COMMENT_SUCCESS: 'SHOW_COMMENT_SUCCESS',
  SHOW_COMMENT_FAILURE: 'SHOW_COMMENT_FAILURE',

  DELETE_COMMENT_SUCCESS: 'DELETE_COMMENT_SUCCESS',
  DELETE_COMMENT_FAILURE: 'DELETE_COMMENT_FAILURE',

  COMMENT_NOT_FOUND: 'COMMENT_NOT_FOUND',

  // Post Responses
  CREATE_POST_SUCCESS: 'CREATE_POST_SUCCESS',
  CREATE_POST_FAILURE: 'CREATE_POST_FAILURE',

  UPDATE_POST_SUCCESS: 'UPDATE_POST_SUCCESS',
  UPDATE_POST_FAILURE: 'UPDATE_POST_FAILURE',

  SHOW_POST_SUCCESS: 'SHOW_POST_SUCCESS',
  SHOW_POST_FAILURE: 'SHOW_POST_FAILURE',

  DELETE_POST_SUCCESS: 'DELETE_POST_SUCCESS',
  DELETE_POST_FAILURE: 'DELETE_POST_FAILURE',

  POST_NOT_FOUND: 'POST_NOT_FOUND',
  NO_POSTS_FOUND: 'NO_POSTS_FOUND',
  POSTS_FOUND: 'POSTS_FOUND'
}
